GET http://localhost:5000/home 


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "userName" : "Jeevn",
    "password" : "jeevan123"
}

###
POST http://localhost:5000/register
Content-Type : application/json

{
    "userName" : "Jeevann",
    "email" : "jeevan1@gmail.com",
    "password" : "jeevan123",
    "confirmPassword" : "jeevan123"
}